### ISSUE TITLE
Q: Is there any ready to use SMPP server?

### ISSUE THREAD

**Issue by theLastOfCats** [funbox/smppex#75]
Hi!

At the moment I'm looking robust SMPP server in order to replace [Selenium SMPPSim](www.seleniumsoftware.com/user-guide.htm).

Are there any sources of [smppex.rubybox.ru](smppex.rubybox.ru)?
If not, as I understand, I will need to implement a server based on `SMPPEX.MC`?

**Comment by savonarola** [comment]
Hello!

>I will need to implement a server based on SMPPEX.MC?

In general, yes, you need to implement actual PDU handling.

>Are there any sources of smppex.rubybox.ru?

Yes, they are here: https://github.com/savonarola/smppex_web

**Comment by theLastOfCats** [comment]
Looks awesome, thanks!
