### ISSUE TITLE
Why is poison a dependency?

### ISSUE THREAD

**Issue by IceDragon200** [funbox/smppex#83]
I see no usage of Poison in the codebase, so why is it a dependency? Even if it's optional it has caused havoc in my codebase as of late with libraries that support both jason and poison since mix pulls it in regardless.

**Comment by savonarola** [comment]
Hello!
`Poison` really seems to bu unused. 

https://hex.pm/packages/smppex/3.0.2

**Comment by IceDragon200** [comment]
Thanks for the quick reply, I guess I can close this issue now
